/**
 * @file 不规范issue则自动关闭
 * @author xuexb <fe.xiaowu@gmail.com>
 */

const format = require('string-template')
const {
  commentIssue,
  closeIssue,
  addLabelsToIssue
} = require('../../github')

const comment = [
  'Hello, this issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://www.iviewui.com/new-issue) to create an issue - thank you!'
].join('')

function replyInvalid (on) {
  on('issues_opened', ({ payload }) => {
    const issue = payload.issue
    const opener = issue.user.login

    if (issue.body.indexOf('<!-- generated by iview-issues. DO NOT REMOVE -->') === -1) {
      commentIssue(
        payload,
        format(comment, {
          user: opener
        })
      )

      closeIssue(payload)
      addLabelsToIssue(payload, 'invalid')
    }
  })
}

module.exports = replyInvalid
